version: '3.8'

services:
  app:
    build: .
    ports:
      - "9600:9600"
    environment:
      - NODE_ENV=development
      - PORT=9600
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=template_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=dev-secret-key
      - CORS_ORIGIN=*
      - LOG_LEVEL=debug
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=template_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
